#!/usr/bin/expect -f
set timeout 20
set host [lindex $argv 0]
set user [lindex $argv 1]
set password [lindex $argv 2]
set cmd [lindex $argv 3]
spawn telnet $host
expect "Username:"
send "$user\r"
expect "Password:"
send "$password\r"
expect ">"
send "$cmd\r"
send "exit\r";
interact
